In [1]:
category_df.to_csv(
    'data/processed/category_performance.csv',
    index=False
)

NameError: name 'category_df' is not defined

In [3]:
from google.cloud import bigquery
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    "/Users/student/Downloads/ordermetrics360-1b2c7e064813.json"
)

client = bigquery.Client(
    project="ordermetrics360",
    credentials=credentials
)

category_df = client.query("""
SELECT *
FROM `ordermetrics360.ordermetrics360_marts.mart_category_performance`
""").to_dataframe()

category_df.head()

/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/google/api_core/_python_version_support.py:242: FutureWarning: You are using a non-supported Python version (3.9.6). Google will not post any further updates to google.api_core supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.api_core.
  warnings.warn(message, FutureWarning)
/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        product_category  order_count     revenue  average_review_score
0          health_beauty         8836  1258681.34              4.181203
1          watches_gifts         5624  1205005.68              4.065459
2         bed_bath_table         9417  1036988.68              3.970740
3         sports_leisure         7720   988048.97              4.167362
4  computers_accessories         6689   911954.32              4.026245

In [4]:
category_df.to_csv(
    'data/processed/category_performance.csv',
    index=False
)

In [5]:
delivery_summary_df = client.query("""
SELECT
    CASE
        WHEN delivery_delay_days <= 0 THEN 'On Time / Early'
        ELSE 'Delayed'
    END AS delivery_status,
    COUNT(*) AS order_count,
    ROUND(AVG(review_score), 2) AS average_review_score,
    ROUND(AVG(delivery_delay_days), 2) AS average_delay_days
FROM `ordermetrics360.ordermetrics360_marts.mart_delivery_reviews`
WHERE review_score IS NOT NULL
GROUP BY delivery_status
ORDER BY delivery_status
""").to_dataframe()

delivery_summary_df

/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

   delivery_status  order_count  average_review_score  average_delay_days
0          Delayed         6382                  2.27               10.52
1  On Time / Early        89448                  4.29              -13.51

In [6]:
delivery_summary_df.to_csv(
    'data/processed/delivery_summary.csv',
    index=False
)

In [7]:
revenue_df = client.query("""
SELECT
    order_month,
    order_count,
    revenue,
    average_order_value
FROM `ordermetrics360.ordermetrics360_marts.mart_revenue_trend`
ORDER BY order_month
""").to_dataframe()

revenue_df

/Users/student/OrderMetrics360/venv/lib/python3.9/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

   order_month  order_count     revenue  average_order_value
0   2016-09-01            2      207.86           103.930000
1   2016-10-01          293    44507.30           151.902048
2   2016-12-01            1       10.90            10.900000
3   2017-01-01          787   120098.27           152.602630
4   2017-02-01         1718   244959.35           142.584022
5   2017-03-01         2617   368341.32           140.749454
6   2017-04-01         2377   353842.98           148.861161
7   2017-05-01         3640   503159.19           138.230547
8   2017-06-01         3205   429916.61           134.139348
9   2017-07-01         3946   492287.30           124.756031
10  2017-08-01         4272   568245.79           133.016337
11  2017-09-01         4227   621415.91           147.011098
12  2017-10-01         4547   660179.62           145.190152
13  2017-11-01         7423  1003862.14           135.236716
14  2017-12-01         5620   742183.79           132.061173
15  2018-01-01         7187   945456.29           131.550896
16  2018-02-01         6625   837895.43           126.474782
17  2018-03-01         7168   981051.06           136.865382
18  2018-04-01         6919   993592.98           143.603553
19  2018-05-01         6833   992871.75           145.305393
20  2018-06-01         6145   863265.53           140.482592
21  2018-07-01         6233   878044.27           140.870250
22  2018-08-01         6421   848860.10           132.200607
23  2018-09-01            1      145.00           145.000000

In [8]:
revenue_df.to_csv(
    'data/processed/revenue_trend.csv',
    index=False
)